### PR TITLE
create folder structure

### PR DESCRIPTION
**Pull request by susiekims**
Created initial folder structure: assets and app. In app there's components, containers, and store

### CODE REVIEW

**Review by Kikisek — DISMISSED** [review]
Looks great!

If you want to fix the error in the CI, you can adjust the import on line 3 in the `App.test.js` to `import App from './app/App';`
If you don't feel like doing it, I can do it in another PR later 😄

**Comment by Kikisek** [comment]
Oh, you probably need to fix the CI, otherwise we cannot merge.

**Comment by susiekims** [comment]
Oh oops! I can fix it when I get home

**Comment by susiekims** [comment]
I missed updating the import path in App.test.js, it has been fixed now

**Review by Kikisek — APPROVED** [review]
Perfect!

**Pull request merged**
